"""added days_of_week and time_of_day

Revision ID: eda2dae99fe1
Revises: 8ca6ca970ddf
Create Date: 2025-11-17 22:18:59.900416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda2dae99fe1'
down_revision: Union[str, Sequence[str], None] = '8ca6ca970ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('days_of_week', sa.String(), nullable=True))
    op.add_column('reminders', sa.Column('time_of_day', sa.String(), nullable=True))
    op.drop_column('reminders', 'run_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('run_at', sa.DATETIME(), nullable=True))
    op.drop_column('reminders', 'time_of_day')
    op.drop_column('reminders', 'days_of_week')
    # ### end Alembic commands ###
